/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author BSISTEMAS
 */
public class frmReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReportes
     */
    public frmReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel19 = new javax.swing.JPanel();
        jLabel142 = new javax.swing.JLabel();
        rSPanelsSlider1 = new rojeru_san.RSPanelsSlider();
        pSemanaActual = new javax.swing.JPanel();
        pGraficoSemActual = new javax.swing.JPanel();
        lbSemana1 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        lbSemana2 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        lbSemana3 = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel162 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        pGraficoSemActual1 = new javax.swing.JPanel();
        lbSemana = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("REPORTES");
        setToolTipText("REPORTES");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1ae7aa7b-a29d-4dba-b43c-550486d27399_200x200.png"))); // NOI18N

        jPanel19.setBackground(new java.awt.Color(255, 102, 102));

        jLabel142.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel142.setForeground(new java.awt.Color(255, 255, 255));
        jLabel142.setText("REPORTES");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel142)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel142)
        );

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        pSemanaActual.setBackground(new java.awt.Color(255, 255, 255));
        pSemanaActual.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        pGraficoSemActual.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout pGraficoSemActualLayout = new javax.swing.GroupLayout(pGraficoSemActual);
        pGraficoSemActual.setLayout(pGraficoSemActualLayout);
        pGraficoSemActualLayout.setHorizontalGroup(
            pGraficoSemActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        pGraficoSemActualLayout.setVerticalGroup(
            pGraficoSemActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        lbSemana1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lbSemana1.setForeground(new java.awt.Color(189, 55, 41));
        lbSemana1.setText("Ventas Totales");

        jLabel149.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel149.setForeground(new java.awt.Color(189, 55, 41));
        jLabel149.setText("Venta Promedio");

        jLabel150.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel150.setForeground(new java.awt.Color(189, 55, 41));
        jLabel150.setText("Número de ventas");

        jLabel151.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel151.setForeground(new java.awt.Color(153, 153, 153));
        jLabel151.setText("$");

        jLabel152.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel152.setForeground(new java.awt.Color(153, 153, 153));
        jLabel152.setText("25000.00");

        jLabel153.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel153.setForeground(new java.awt.Color(153, 153, 153));
        jLabel153.setText("25000.00");

        jLabel154.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel154.setForeground(new java.awt.Color(153, 153, 153));
        jLabel154.setText("$");

        jLabel155.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel155.setForeground(new java.awt.Color(153, 153, 153));
        jLabel155.setText("6");

        lbSemana2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lbSemana2.setForeground(new java.awt.Color(189, 55, 41));
        lbSemana2.setText("Ganancia");

        jLabel156.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel156.setForeground(new java.awt.Color(189, 55, 41));
        jLabel156.setText("Maregen de utilidad");

        jLabel157.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel157.setForeground(new java.awt.Color(189, 55, 41));
        jLabel157.setText("promedio");

        jLabel158.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel158.setForeground(new java.awt.Color(153, 153, 153));
        jLabel158.setText("25000.00");

        jLabel159.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel159.setForeground(new java.awt.Color(153, 153, 153));
        jLabel159.setText("$");

        jLabel160.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel160.setForeground(new java.awt.Color(153, 153, 153));
        jLabel160.setText("10");

        jLabel161.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel161.setForeground(new java.awt.Color(153, 153, 153));
        jLabel161.setText("%");

        jLabel143.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        jLabel143.setForeground(new java.awt.Color(153, 153, 153));
        jLabel143.setText(" - - - - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -");

        lbSemana3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lbSemana3.setForeground(new java.awt.Color(189, 55, 41));
        lbSemana3.setText("Ventas por día");

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane21.setViewportView(jList3);

        jLabel162.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel162.setForeground(new java.awt.Color(153, 153, 153));
        jLabel162.setText("$");

        jLabel163.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel163.setForeground(new java.awt.Color(153, 153, 153));
        jLabel163.setText("25000.00");

        pGraficoSemActual1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout pGraficoSemActual1Layout = new javax.swing.GroupLayout(pGraficoSemActual1);
        pGraficoSemActual1.setLayout(pGraficoSemActual1Layout);
        pGraficoSemActual1Layout.setHorizontalGroup(
            pGraficoSemActual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        pGraficoSemActual1Layout.setVerticalGroup(
            pGraficoSemActual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pSemanaActualLayout = new javax.swing.GroupLayout(pSemanaActual);
        pSemanaActual.setLayout(pSemanaActualLayout);
        pSemanaActualLayout.setHorizontalGroup(
            pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSemanaActualLayout.createSequentialGroup()
                .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSemanaActualLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel143, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSemanaActualLayout.createSequentialGroup()
                        .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pSemanaActualLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbSemana1))
                            .addGroup(pSemanaActualLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel150)
                                    .addComponent(jLabel149))))
                        .addGap(68, 68, 68)
                        .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pSemanaActualLayout.createSequentialGroup()
                                .addComponent(jLabel151)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel152, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel155, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pSemanaActualLayout.createSequentialGroup()
                                .addComponent(jLabel154)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel153, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80)
                        .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSemana2)
                            .addGroup(pSemanaActualLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel156)
                                    .addComponent(jLabel157))))
                        .addGap(62, 62, 62)
                        .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pSemanaActualLayout.createSequentialGroup()
                                .addComponent(jLabel159)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel158, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pSemanaActualLayout.createSequentialGroup()
                                .addComponent(jLabel160)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel161, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83)
                        .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSemana3)
                            .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pSemanaActualLayout.createSequentialGroup()
                                    .addComponent(jLabel162)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel163, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSemanaActualLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pGraficoSemActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pGraficoSemActual1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pSemanaActualLayout.setVerticalGroup(
            pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSemanaActualLayout.createSequentialGroup()
                .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pGraficoSemActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pGraficoSemActual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel143)
                .addGap(18, 18, 18)
                .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSemanaActualLayout.createSequentialGroup()
                        .addComponent(lbSemana1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel150)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel149))
                    .addGroup(pSemanaActualLayout.createSequentialGroup()
                        .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel151)
                            .addComponent(jLabel152))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel155)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel154)
                            .addComponent(jLabel153)))
                    .addGroup(pSemanaActualLayout.createSequentialGroup()
                        .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSemana2)
                            .addComponent(jLabel159)
                            .addComponent(jLabel158)
                            .addComponent(lbSemana3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pSemanaActualLayout.createSequentialGroup()
                                .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel156)
                                    .addComponent(jLabel160)
                                    .addComponent(jLabel161))
                                .addGap(1, 1, 1)
                                .addComponent(jLabel157))
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pSemanaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel162)
                    .addComponent(jLabel163))
                .addContainerGap())
        );

        rSPanelsSlider1.add(pSemanaActual, "card2");

        lbSemana.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbSemana.setForeground(new java.awt.Color(189, 55, 41));
        lbSemana.setText("Semana Actual");

        jLabel144.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel144.setForeground(new java.awt.Color(153, 153, 153));
        jLabel144.setText("Resumen de Ventas de la Semana Actual");

        jLabel145.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel145.setForeground(new java.awt.Color(189, 55, 41));
        jLabel145.setText("Mes Actual");

        jLabel146.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel146.setForeground(new java.awt.Color(189, 55, 41));
        jLabel146.setText("Mes Anterior");

        jLabel147.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel147.setForeground(new java.awt.Color(189, 55, 41));
        jLabel147.setText("Año Actual");

        jLabel148.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel148.setForeground(new java.awt.Color(189, 55, 41));
        jLabel148.setText("Periodo...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel144)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbSemana)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel145)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel146)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel147)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel148)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel144)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSemana)
                    .addComponent(jLabel145)
                    .addComponent(jLabel146)
                    .addComponent(jLabel147)
                    .addComponent(jLabel148))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JLabel lbSemana;
    private javax.swing.JLabel lbSemana1;
    private javax.swing.JLabel lbSemana2;
    private javax.swing.JLabel lbSemana3;
    private javax.swing.JPanel pGraficoSemActual;
    private javax.swing.JPanel pGraficoSemActual1;
    private javax.swing.JPanel pSemanaActual;
    private rojeru_san.RSPanelsSlider rSPanelsSlider1;
    // End of variables declaration//GEN-END:variables
}
